version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4433:4433"
    restart: unless-stopped
    depends_on: 
      - redis
    networks:
      - backend

  redis:
    image: "redis:latest"
    restart: unless-stopped
    networks:
      - backend

networks:
 backend: